image: node:${NODE_JS_VERSION}

stages:
  - install
  - test-lint
  # - build
  # - build image
  # - deploy

install:
  stage: install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm install

eslint:
  stage: test-lint
  before_script:
    - npm install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - node_modules/
  script:
    - npm run eslint

#test:
#  stage: test-lint
#  before_script:
#    - npm install
#  cache:
#    key: $CI_COMMIT_REF_SLUG
#    paths:
#    - node_modules/
#  services:
#    - mysql:5.7.25
#    - rabbitmq:3.7.15-alpine
#  variables:
#    MYSQL_HOST: mysql
#    MYSQL_USER: cargoo
#    MYSQL_PASSWORD: qwerty
#    MYSQL_ROOT_PASSWORD: qwerty
#    MYSQL_DATABASE: user_service
#    USER_SERVICE_MYSQL_DB: user_service
#
#    RABBIT_HOST: rabbitmq
#    RABBIT_PORT: 5672
#    RABBIT_PASSWORD: guest
#    RABBIT_USER: guest
#
#    NODE_ENV: test
#  script:
#    - npm run migrate
#    - npm run test

# build:
#   stage: build
  # before_script:
  #   - npm install
  # cache:
  #   key: $CI_COMMIT_REF_SLUG
  #   paths:
  #     - node_modules/
#   script:
#     - npm run build
#   artifacts:
#     name: dist-full
#     paths:
#       - dist/
#   only:
#     - master

# build image:
#   image: docker:stable
#   stage: build image
#   services:
#     - docker:dind
#   script:
#     - docker build -t registry.gitlab.com/cargoo/core-service:dev .
#     - docker login -u cargoo.machineuser@gmail.com -p $DOCKER_REGISTRY_PASSWORD registry.gitlab.com
#     - docker push registry.gitlab.com/cargoo/core-service:dev
#   dependencies:
#     - build
#   only:
#     - master

# deploy:
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - eval "$(ssh-agent -s)"
#     - ssh-add ~/.ssh/id_rsa
#     - ssh-keyscan -H 'ec2-34-201-0-89.compute-1.amazonaws.com' >> ~/.ssh/known_hosts
#   stage: deploy
#   script:
#     - ssh $CI_USER@$DEV_HOST < deploy.sh
#   only:
#     - master
#   when: manual
#   environment:
#     name: dev
#     url: http://cargoo.com.ua
