image: node:${NODE_JS_VERSION}

stages:
  - install
  - test-lint

install:
  stage: install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - npm install

eslint:
  stage: test-lint
  before_script:
    - npm install
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - node_modules/
  script:
    - npm run eslint
