const moment = require('moment');

module.exports = {
  name: 'core-service',
  env: 'production',
  envShort: 'prod',
  sendGridApiKey: '',
  port: 6007,
  apiPrefix: '/api/v1',
  sessionSecret: '',
  enableCORS: false,
  requestTimeout: 10000,
  services: {},
  adminEmail: 'cargoo.delivery@gmail.com',
  emailVerificationPath: '/email-verification',
  appId: '18dcbb60-f092-11e7-9ea0-05a976ec92c7',
  proxyUrl: '',
  cmsApiKey: '',
  resetPasswordPath: '/reset-password',
  logLevel: 'warn',
  bcryptIterations: 8,
  mongoDB: {
    host: '127.0.0.1',
    user: '',
    password: '',
    database: '',
    port: 27017,
  },
  db: {
    host: '127.0.0.1',
    user: '',
    password: '',
    database: '',
    port: 3306,
    dialect: 'mysql',
    logging: false,
  },
  redis: {
    host: '',
    password: '',
  },
  rabbit: {
    host: '127.0.0.1',
    user: '',
    password: '',
    port: 5672,
  },
  jwt: {
    userSecret: '',
    clientSecret: '',
    resetSecret: '',
    verifySecret: '',
    accessTimeout: moment.duration(1, 'hour').asSeconds(),
    resetTimeout: moment.duration(1, 'day').asSeconds(),
    verifyTimeout: moment.duration(1, 'day').asSeconds(),
  },
};
